package Broker

const (
	COMMAND_REDIS_RPUSH = int32(iota + 1000)
	COMMAND_REDIS_BLPOP
	COMMAND_REDIS_BRPOP
	COMMAND_REDIS_PUBLISH
	COMMAND_REDIS_SUBSCRIBE
	COMMAND_REDIS_UNSUBSCRIBE
	COMMAND_REDIS_RECEIVEMESSAGE
)
