package broker

const (
	BROKER_ERROR_CODE_SUCCESS = iota + 200
	BROKER_ERROR_CODE_NOT_EXIST_WORKER
	BROKER_ERROR_CODE_MANAGER_CHANNEL_OVERFLOW
	BROKER_ERROR_CODE_CUSTOM_CHANNEL_OVERFLOW
	BROKER_ERROR_CODE_CLIENT_DISCONNECT
	BROKER_ERROR_CODE_CHANNEL_CLOSED
	BROKER_ERROR_CODE_CMD_RESULT_DONE
	BROKER_ERROR_CODE_MAKE_REQUEST_FAIL
	BROKER_ERROR_CODE_BCURL_HTTP_URL_NOT_SET
	BROKER_ERROR_CODE_BCURL_HTTP_METHOD_NOT_SET
	BROKER_ERROR_CODE_BCURL_HTTP_POST_FIELD_NOT_SET
	BROKER_ERROR_CODE_BCURL_HTTP_RESPONSE_FAIL
	BROKER_ERROR_CODE_BCURL_HTTP_READ_RESPONSE_BODY_FAIL
)

type ErrorCodeType int
type Error struct {
	ErrorCode ErrorCodeType
	Source    interface{}
	Content   interface{}
}
