package broker

const (
	BROKER_ERROR_CODE_SUCCESS = iota + 200
	BROKER_ERROR_CODE_MANAGER_CHANNEL_OVERFLOW
	BROKER_ERROR_CODE_CUSTOM_CHANNEL_OVERFLOW
	BROKER_ERROR_CODE_CLIENT_DISCONNECT
	BROKER_ERROR_CODE_CHANNEL_CLOSED
)

type ErrorCodeType int
type Error struct {
	ErrorCode ErrorCodeType
	Content   interface{}
}
